Review 1
87Igor/cpp-peer-review pull request #3
Opened 2023-10-08 13:44 UTC by 87Igor

2023-10-08 17:06 UTC, Mishgun01 requested changes
Отличная работа, посмотри рекомендации

2023-10-08 17:06 UTC, Mishgun01 commented on task_1.cpp
> +        switch (info_req.type_req)
отлично использовал enum class

2023-10-08 17:06 UTC, Mishgun01 commented on task_1.cpp
> +
Там в условии мы не обрабатываем некорректный ввод, можно переписать проще

2023-10-08 17:06 UTC, Mishgun01 commented on task_1.cpp
> +struct InfoReq {
Отличная структура!

2023-10-08 17:06 UTC, Mishgun01 commented on task_1.cpp
> +
строки 37-43 можно объединить, если пользователь уже есть работать с страницами, так получается лишнее действие (добавил-удалил)

2023-10-10 18:36 UTC, 87Igor commented on task_1.cpp
> +
Не вижу где добавляю - удаляю (.
в 37 строке получаю кол-во страниц прочитанное пользователем, до изменения.
в 38 записываю новое значение прочитанных страниц  в page_num_read_user.
далее проверяю если по индексу до изменения было значение больше 0(т.е. наш пользователь был добавлен в вектор по индексу прочитанных страниц) тогда уменьшаю на единицу. Так как у пользователя уже другое кол-во страниц и другой индекс в векторе count_user_read_page.

2023-10-10 18:40 UTC, 87Igor commented on task_1.cpp
> +
Оставлю так для универсальности. Может в будущем появится необходимость в проверках при вводе.

2023-10-11 06:33 UTC, merged